apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: labenv
spec:
  selector:
    app: mysql
  ports:
  - name: default
    protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None
#  type: ClusterIP