version: "3.1"

services:

  mysql:
    container_name: mysql-bank
    image: mysql:latest
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bank
    ports:
      - 3306:3306

  java-app:
    container_name: bank-app
    image: bank:1.0.0
    ports:
      - 8081:8080
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql
