version: "3.1"

services:

  risk-assessment:
    container_name: risk-service
    image: daneidmark/risk:0.0.1
    ports:
      - 8082:8080

  mysql:
    container_name: mysql-bank
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bank
      MYSQL_TCP_PORT: 3307
    ports:
      - 3309:3306

  java-app:
    container_name: bank-app
    image: dalle90/bank:latest
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql
      RISK: risk-assessment:8080
    depends_on:
      - mysql