version: "3.1"

services:

  mysql:
    container_name: backend2_mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bank
#      MYSQL_USER: newuser
#      MYSQL_PASSWORD: password

  java-app:
    container_name: bank_app
    image: bank:1.0.0
    ports:
      - 8081:8080
    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bank #?autoReconnect=true&useSSL=false
      MYSQL_HOST: mysql
#      MYSQL_PORT: 3306
#      MYSQL_NAME: bank
#      MYSQL_USER: newuser
#      MYSQL_PASSWORD: password
    depends_on:
      - mysql
