version: "3.1"

services:
#  mongo:
#    image: mongo
#    ports:
#      - 27017:27017
#    volumes:
#      - data/db
#
#  java-app:
#    image: dalle90/nilecity-appen:latest
#    ports:
#      - 8083:8080
#    environment:
#      SPRING_PROFILES_ACTIVE: prod
#      DB_HOST: mongo
#      DB_PORT: 27017
#      DB_NAME: nilecity-enterprises-prod-db
#    depends_on:
#      - mongo

  mysql:
    image: mysql:latest
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bank
      MYSQL_USER: newuser
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
#    volumes:
#      - /var/lib/mysql
#    command: --init-file /data/application/init.sql

  java-app:
    image: bank:1.0.0
    ports:
      - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bank #?autoReconnect=true&useSSL=false
#      MYSQL_HOST: mysql
#      MYSQL_HOST: localhost
#      MYSQL_PORT: 3306
#      MYSQL_NAME: bank
    depends_on:
      - mysql
