apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-deployment
  namespace: labenv
  labels:
    app: risk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk
  template:
    metadata:
      labels:
        app: risk
    spec:
      containers:
        - name: risk
          image: daneidmark/risk:0.0.1
          imagePullPolicy: IfNotPresent