apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deployment
  namespace: labenv
  labels:
    app: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank
          image: dalle90/bank:latest
          imagePullPolicy: IfNotPresent